// Generated by CoffeeScript 1.6.2
(function() {
  var app, express, qs, server, ss, system, url, utils;

  express = require("express");

  url = require('url');

  qs = require('querystring');

  app = express();

  utils = require('./lib/client/serve/utils');

  system = require('./lib/client/system');

  app.use(express["static"](__dirname + "/public"));

  ss = require('./lib/socketstream');

  ss.client.define('main', {
    view: 'app.html',
    css: ['libs/reset.css', 'app.styl'],
    code: ['libs/jquery.min.js', 'app'],
    tmpl: '*'
  });

  app.get('/_serveDev/system?*', function(request, response) {
    return utils.serve.js(system.serve.js(), response);
    /*
    # Listen for requests for application client code
    app.get '/_serveDev/code?*', (request, response) ->
    thisUrl = url.parse(request.url)
    params = qs.parse(thisUrl.query)
    path = utils.parseUrl(request.url)
    asset.js path, {pathPrefix: params.pathPrefix}, (output) ->
      utils.serve.js(output, response)
    */

  });

  app.get('/_serveDev/start?*', function(request, response) {
    return utils.serve.js(system.serve.initCode(), response);
  });

  /*
  app.get '/_serveDev/css?*', (request, response) ->
    path = utils.parseUrl(request.url)
    asset.css path, {}, (output) ->
      utils.serve.css(output, response)
  */


  server = app.listen(3001);

  console.log("Express started on port 3000");

}).call(this);
